services:
    vivait_generator.generator.listener:
        class: Vivait\StringGeneratorBundle\EventListener\GeneratorListener
        public: false
        arguments:
            - "@annotation_reader"
            - "@vivait_generator.registry"

        tags:
            - { name: doctrine.event_listener, event: prePersist }

    vivait_generator.registry:
        class: Vivait\StringGeneratorBundle\Registry\Registry

    vivait_generator.generator.string:
        class: Vivait\StringGeneratorBundle\Generator\StringGenerator
        tags:
            - { name: vivait_generator.generator, alias: 'string' }

    vivait_generator.generator.secure_bytes:
        class: Vivait\StringGeneratorBundle\Generator\SecureBytesGenerator
        tags:
            - { name: vivait_generator.generator, alias: 'secure_bytes' }

    vivait_generator.generator.secure_string:
        class: Vivait\StringGeneratorBundle\Generator\SecureStringGenerator
        arguments:
            - "@vivait_generator.randomlib"
        tags:
            - { name: vivait_generator.generator, alias: 'secure_string' }

    vivait_generator.generator.uuid_string:
        class: Vivait\StringGeneratorBundle\Generator\UuidGenerator
        tags:
            - { name: vivait_generator.generator, alias: 'uuid_string' }

    vivait_generator.randomlib:
        class: RandomLib\Factory
